---
- hosts: all
  sudo: yes
  roles:
    - angstwad.docker_ubuntu
  vars:
    hostname: fountainhead-stat.us
    bind_port: 5000
  tasks:
    - include_vars: vars.yml
    - include_vars: secrets.yml
    - name: db container
      docker:
        name: fountainheadstatus-db
        image: postgres
        state: started
        restart_policy: always
    - name: web container
      docker:
        name: fountainheadstatus-web
        image: dschep/fountainhead-status
        state: reloaded
        restart_policy: always
        pull: always
        ports:
          - "{{ bind_port }}:5000"
        links:
          - fountainheadstatus-db:db
        env:
          SQLALCHEMY_DATABASE_URI: "{{ SQLALCHEMY_DATABASE_URI }}"
          ACCOUNT_SID: "{{ ACCOUNT_SID }}"
          AUTH_TOKEN: "{{ AUTH_TOKEN }}"
          FROM: "{{ FROM }}"
          SERVER_URL: "{{ SERVER_URL }}"
    - name: install nginx
      apt: pkg=nginx state=present
    - name: copy nginx site
      template: src=nginx-site dest=/etc/nginx/sites-enabled/fountainheadstatus
      notify:
        - restart nginx
    - name: crontab to update status
      cron: name="update Fountainhead status" minute="0" hour="*/2"
            job="docker exec fountainheadstatus-web python fountainheadstatus.py update"
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
